name: laporan_toko
description: Sistem Laporan Toko - Flutter Native
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_database: ^10.5.0
  device_info_plus: ^10.1.0
  http: ^1.2.0
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.12.0

flutter:
  uses-material-design: true